title: practice
theme: minima  # 使用默认主题，请不要设为 null 否则页面没有样式
markdown: kramdown
url: "https://hli199305-ee.github.io"
baseurl: "/HLi199305-ee.github.io-practice"  # 很重要！必须加上你的仓库名

kramdown:
  toc_levels: 2..3

exclude:
  - /backup
  - /pages/todo
  - /vendor
  - /Gemfile
  - /Gemfile.lock
  - /LICENSE

plugins:
  - jekyll-relative-links
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""
  query: "@*"
